# Generated by Django 4.2.6 on 2023-10-22 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_like_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="liked_at",
        ),
        migrations.AddField(
            model_name="like",
            name="liked_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
