# Generated by Django 4.2.6 on 2023-10-19 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_request_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
