# Generated by Django 4.2.6 on 2023-10-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Invalid email address"
                    )
                ],
                verbose_name="email address",
            ),
        ),
    ]
